logging:
  level:
    ROOT: INFO

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

management:
  security:
    enabled: false

spring:
  rabbitmq:
    host: rabbitmq