version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672

### start includes ####

  config-server:
    image: config-server
    restart: always
    ports:
      - 8888:8888
    volumes:
      - /root:/root

  discovery-server:
    image: discovery-server
    restart: always
    ports:
      - 8761:8761

  gateway-server:
    image: gateway-server
    restart: always
    ports:
      - 80:4000

  monitoring-server:
    image: monitoring-server
    restart: always
    ports:
      - 9000:8989
      - 8080:8080

### end includes ######
