spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
#          uri: https://github.com/winechess/test-spring-cloud
#          searchPaths: config-repo
server:
  port: 8888
management:
  security:
    enabled: false
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: f865230af8c84
    alias: config-server
    secret: f865230af8c84
security:
  basic:
    enabled: false