spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/winechess/test-spring-cloud
          searchPaths: config-repo
server:
  port: 8888
management:
  security:
    enabled: false